### ISSUE TITLE
CSS动画

### ISSUE THREAD

**Issue by jesusalexander** [jesusalexander/jesusalexander.github.io#107]
前端是直接承载用户体验和设计呈现的重任的一个角色。随着Web应用越来越复杂，前端技术也被时代逼着越来越复杂，例如模块化、跨平台、响应式和动画。今天的主题就是其中之一 — 动画。

如今动画已经是前端技术中不可或缺的一部分了，能如此的普及前端动画要归功于CSS3。直到CSS3出现，	前端动效才真正的在前端占一席之地。

在CSS3普及前的技术：

- 纯操作DOM
- 使用Flash
- Silverlight

以上Flash和Silverlight基本上因为性能、兼容性问题已经被时代淘汰了。而纯操作DOM实现的动画也可以被纯CSS3动画所取代。

希望本文能给想写前端动画的同学提供一些帮助，可以更快的入门和写效果。

接下来会介绍几个内容：
 - 补间动画
 - 逐帧动画
 - 动画工具
 - 在Angular中使用动画

#补间动画

补间动画是前端交互的大头，大部分的前端交互都是以渐进渐出这样的补间动画的表现，显得操作自然不突兀。

![linear](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/linear.png?raw=true)

所谓补间动画，就是人为创建关键帧，由渲染机制自己创建和渲染关键帧之间的动画帧。所以我们只需要定义动画状态的即可完成动画。

## Transition

CSS3 的 transition 可以让我们很方便的创建一个动画。

我们只需设置初始状态，和触发后状态既可以完成一个动画：

```CSS
.a {
  height: 100px;
  transition: 0.3s all linear;
}
.a.active {
  height: 200px;
}
```

如上所示，只需在标签中添加 transition 属性，那么它属性的变化将以过渡的方式变化。

transition属性中：

 - `0.3s` 是动画时间
 - 参数 `all` 是需要过渡的属性
 - `linear` 是描述动画速度的曲线，官方文档称为`time-function`。

更详尽的参数可以查看官方文档，会有更详尽的解释。

一个动画自不自然，炫不炫酷，靠的是第三个属性，也就是以上代码的linear。

### time-function

以下是linear的曲线，可以看到是一条直线，意味着过渡动画是以匀速进行的。

![linear](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/linear.png?raw=true)

![](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/linear-demo.gif?raw=true)

这种动画基本上不是一个自然的动画，因为在实践的物体运动中，肯定会有加速度变化的，所以我们可以调整它的运动曲线，将linear改为ease-in-out。

![ease-in-out](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/ease-in-out.png?raw=true)

![](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/ease-demo.gif?raw=true)

如图所示，该动画是以一个加速、匀速再减速的方式进行，这样更符合实际中的运动规律。

有时我们需要的不止是简单的加速减速效果了，那么我们可以自定义运动曲线来达到我们需要的效果，如图我们可以做出弹簧运动的效果。

![in-out-back](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/in-out-back.png?raw=true)

![](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/in-out-back-demo.gif?raw=true)

当然，此时的属性值也不是简单的linear、ease-in-out可以表达的，上面的曲线的属性值是`cubic-bezier(0.68, -0.55, 0.27, 1.55)`

这里涉及到一个概念：`贝塞尔曲线`。

所谓`贝塞尔曲线`就是由几个点来描述的曲线。

这是一个二次贝塞尔曲线，由三个点即两个线段表示。

![Bézier_2_big](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/B%C3%A9zier_2_big.gif?raw=true)

而cubic-bezier属性，是三次贝塞尔曲线，即四个点，三个线段表示。

![Bézier_3_big](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/B%C3%A9zier_3_big.gif?raw=true)

贝塞尔的具体参数是cubic-bezier(X1, Y1, X2, Y2)，另两个固定点的坐标是(0,0) (1,1) 与两个入参形成四个点，完成一个三次贝塞尔曲线。

当然，作为应用者来说，我们不需要知道太多，这些坐标参数可以由做动效的同学给出，也可以自己用工具制作，如chrome的开发者工具就很好的对付大部分场景了。

[在线贝塞尔](https://cubic-bezier.com/#.54,-0.72,.25,1.66)

了解完贝塞尔曲线，我们就可以使用transition在完成交互上的大部分动效了。

总的来说，transition 的优点就是使用简单，配合贝塞尔可以做出很炫酷和自然的交互效果。

### transition 的局限
但transition的使用也是有自己的局限的。

- 需要手动触发。例如手动改变一个有transition的节点的高来触发一个动画的产生，而无法在页面加载后就自动的运行动画。
- 一次性动画。一次过渡动画完成后，无法持续循环的继续动画了，除非再次手动触发。
- 无法定义多个关键帧。这意味着只能有初始和结束状态，无法再添加中间状态了。
- 同时只能发生一种transition动画。

所以当我们需要一个多关键帧、多次播放等一些更复杂的动画时，我们就需要animation了。

## animation

在transition动画中，动画靠的是贝塞尔曲线，也只有开始和结束两种状态，而animation动画中就不会有这种限制了，我们可以给一个动画分N种状态，而且我们还可以叠加动画。

Animation 写起来相对复杂一些，需要一个 @keyframes 来定义动画状态：

```CSS
a{
  animation: 1s myAnimation infinite ease-in;
}

@keyframes myAnimation {
  0% { width: 0px; }
  50% { width: 100px; }
  100% { width: 50px;  color: #FFF}
}

```

我们可以给一个动画设置以下参数：

- 动画持续时间
- 动画的Keyframes
- 动画播放次数
- 动画延迟开始的时间
- 动画播放的方向（正放或倒放）
- 每个关键帧的动画速度曲线（贝塞尔曲线）

### keyframes

通过 keyframes 我们可以对动画的进度设置的多个关键帧，由此可以做多个状态变化的动画。

### 动画速度曲线

像transition动画一样，我们可以用贝塞尔曲线来表现动画，需要注意的是，这里的速度曲线不是整体动画的速度，而是关键帧之间的速度。通过设置速度曲线可以更强有力的表现一个动画，如下面这段代码。

```CSS
.a {
  display: inline-block;
  animation: 1s myAnimation infinite cubic-bezier(0.68, -0.55, 0.27, 1.55);
  transform-origin: 50% 50%;
}

@keyframes myAnimation {
  20% {
    transform: scale(1.5);
  }
}
```

这是一个在20%进度时，物体放大1.5倍，开始和结束时1倍的动画

DEMO: [codepen 心跳1](https://codepen.io/jesusalexander/pen/KjjKWq)

加入抖动的速度曲线得到心脏的抖动，显得自然。

> cubic-bezier(0.68, -0.55, 0.27, 1.55);

DEMO: [codepen 心跳2](https://codepen.io/jesusalexander/pen/ZdNPxR)

### 状态叠加

animation 一个很强大的地方是其状态是可以叠加的，这样我们可以很好的管理各种动画状态。

```CSS
.a {
  animation: 1s aniScale infinite,
    2s aniColor infinite;
  width: 100px;
  height: 100px;
  background: #CCC;
}

@keyframes aniScale {
  20% {
    transform: scale(1.5);
  }
}

@keyframes aniColor {
  50% {
    background: red;
  }
  80% {
    background: #FFF:
  }
}
```

上面的例子我们定义了两种动画状态，一个是1秒为周期的形变，一个是2秒为周期颜色变化，如果我们需要还可以加上例如运动等变化。

有时同个运动周期有多种动画可以写进一个动画状态中，例如：

```CSS
.a {
  animation: 1s aniScaleAndColor infinite;
  background: #FFF;
}
@keyframes aniScaleAndColor {
  20% {
    transform: scale(1.5);
    background: red;
  }
}
```

## 一个DEMO

补间动画我们就用一个常见的Loading动画作为结尾

[DEMO](https://codepen.io/jesusalexander/pen/ZddwaQ)

## 动效库

现在的前端动效已经有非常多的开源库可以使用了，不需要高度自定义的动画我们可以用一些第三方库去解决，下面是一些我用过的库和大家介绍一下，在需要快速实现业务动效的时候可以用上。

### animation.css

[animation.css](https://daneden.github.io/animate.css/)

这是一个基础动效库，里面实现了大部分日常使用到的动效，例如抖动，渐入渐出。

在没特定需求的情况下使用这个库来做交互优化是最省时省力的了。

### bouncejs

[bouncejs](http://bouncejs.com)

这不是一个库，而是一个动画生成器，我们可以用它来生成一个基础动画样板，并调整参数从而达到自己想要的效果。bouncejs最吸引人的地方就是它的基础动画样板，通常都是由几种形变结合打造成一个非常自然的动画效果，而且这个工具的用户体验也非常不错，值得体验。

bouncejs的一个问题是其生成的代码用的是css3的matrix3d属性，拥有大量的矩阵参数，所以生成的代码比较大，而且很难阅读，直接使用是没有关系，但是二次修改是基本不可能的事情了。

# 逐帧动画

逐帧动画在前端中使用的并不多，大部分的动画都可以用补间动画代替，甚至包括形变。

一些无法用补间动画代替的就需要逐帧动画出马了，典型的应用场景就是形象事物的动画。

![](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/animationStep.png?raw=true)

## GIF

GIF是应用最广泛的逐帧动画方案了，其以图片的方式加载，无需敲代码，使用起来非常方便。使用最多的场景就是聊天表情包和前端的Loading图。

GIF在以下场景是非常实用的：

- Loading图
- 表情包
- 无法补间动画实现的页面挂件

可以看到，这些使用场景，都有个共同点：小、几乎没有交互操作。

为什么其他动画场景不用GIF代替呢？最主要的原因是GIF的质量和体积以及无法交互的限制。

#### 质量差

GIF 只支持256色，这种色域几乎无法支持稍微有质量要求动画了。

#### 体积大

同等质量，MP4的体积比GIF小了非常多，许多压缩直接达到98%的压缩量，也因此许多有强烈压缩动图体积的应用已经将GIF转为MP4进行加载播放了，如Twitter、Imgur等

#### 无法交互

因为GIF自身的限制，我们无法控制GIF的播放，也因此我们无法做到以下需求：

- 播放暂停
- 前进后退
- 播放次数

所以GIF只能用于无交互需求的动画了。

其他类似GIF的动图方案：Webp、APNG， 都因兼容性无法非常普及。

## CSS实现逐帧动画

在CSS中实现逐帧动画，主要靠雪碧图+animation step来实现。

将所有动画帧平铺，合成一张图，由animation来控制background position显示的画面作为当前帧。

```CSS
.anim {
  animation: sit 900ms steps(14) alternate infinite;
}


@keyframes sit {
  0%   { background-position: 0 0; }
  100% { background-position: -1960px 0; }
}
```

`steps` 是总共播放的步数，分为14步 移动完 0%-100% 的 background-position。

`steps` 有两参数，第一个参数是动画分割的次数，第二个是动画以哪种方式开始，如steps(1, start)是动画开始时，以第一帧作为开始帧，直接显示第二帧。steps(1, end)是以第一帧为开始帧，播放完毕后显示第二帧。

![](https://github.com/jesusalexander/jesusalexander.github.io/blob/master/images/step.png?raw=true)

此时，用CSS实现的逐帧动画可以用一些动画属性来控制播放状态了：

- animation-play-state 控制播放或暂停
- animation-direction 控制动画前进或后退
- animation-fill-mode 控制动画为开始前状态或结束状态

虽然麻烦了一些，但是摆脱了GIF的限制，质量和大小也比GIF更加容易控制。

TODO:DEMO
